name: Deploy

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: npm i
      - name: Imprimir Variables
        run: echo ${{ secrets.STAGE }}
      - name: Deploy
        run: npm run deploy
